### ISSUE TITLE
Latitude between magnetic and electric field instrument are different.

### ISSUE THREAD

**Issue by CassandraAuri** [ESA-VirES/VirES-Python-Client#114]
[LatitudeViresError.pdf](https://github.com/user-attachments/files/17081096/LatitudeViresError.pdf)

So I have been looking at the Electric and magnetic fields during an event and noticed that the coordinates are different by 10's of kilometers during my event in 2022; while years during the same time have been fine.

Is this a data error or vires error. Either way these scales are large enough to make my results questionable.

![image](https://github.com/user-attachments/assets/cba53fb5-857e-495e-86d5-f70ed6f0b271)
![image](https://github.com/user-attachments/assets/a1acd29e-3d70-49d8-b496-20adf3e66ea8)

**Comment by pacesm** [comment]
VirES takes the data, as they are, from the Swarm products. I.e., if there is any discrepancy between the EFI and MAG products locations then it comes from the original Swarm products.

Looking at the difference in latitude (see figure below), the discrepancy in latitude is clearly aligned with the spacecraft orbit and the actual distance between the EFI and MAG locations is consistently ~5.5 meters.

![image](https://github.com/user-attachments/assets/861e9fda-9f91-4d87-8810-da7ae47ec9e3)
 
Looking at the dimensions of the Swarm spacecrafts 

![image](https://github.com/user-attachments/assets/cce8771c-eb79-48ee-ba33-a7d91fda5d6e)

and the location of the sensors

![image](https://github.com/user-attachments/assets/ac824f75-104d-4fa0-bc62-63b8f7a4b509)

it seems like the MAG products locations include offset to the VFM sensor while the EFI products locations seems to be just the location of the spacecraft (see below the same comparison between EFI and MOD/SC products).

![image](https://github.com/user-attachments/assets/705287cf-74f5-457c-b621-34d320020d63)

(The EFI locations were interpolated to 1 Hz MAG/LR and MOD/SC products using cubic spline interpolation.)

**Comment by CassandraAuri** [comment]
Hello Pacesm, I appreciate the detailed response.

I understand that this is a gap between the EFI and VFM of approx 5m to avoid contamination and have replicated this in my jupyter notebook; however, for my event, the distance is 0.06 degrees with cubic spline interpolation (6.66km) which cant be physical and is what I am seeing in the gap in the line plot earlier. For now, I will use the EFI data on the spacecraft so hopefully, that is the correct position. Below is the difference between 2020 and 2022 using absolute differences of the latitudes. As this is not a VIRES issue I am closing this thread but I was wondering if there was an email or person I could direct this to as it is
[LatitudeViresError2.pdf](https://github.com/user-attachments/files/17085776/LatitudeViresError2.pdf)
 It's probably not an issue with any big statistical studies but 7km can make a big difference when overplotting the vector lines(where I noticed this).


![image](https://github.com/user-attachments/assets/83bf271f-1316-40e0-9a38-8b0c2a5b3edb)


![image](https://github.com/user-attachments/assets/327dd69a-278a-4c9a-a245-c211bc72a7d6)

**Comment by pacesm** [comment]
Understood. Not a VirES issue. FYI, for the plots above I picked a random date in 2022. 
May I you to share the more details about your data request? (time, collections, variables, etc.) I'd like to reproduce the problem. 
~7 km distance seems to be really a lot. If it is indeed a data issue, IMO, it should be reported to the Swarm team.

**Comment by CassandraAuri** [comment]
The datetime is 2022,12,19,14 in YY/MM/DD/HH, I'm using swarm B's EFI and VFM and the are visually separated when plotting latitude as a function of time over a two minute window as seen in the initial figure.

**Comment by smithara** [comment]
I have been looking into this a bit. We've confirmed there is no issue with the L1b product `SW_OPER_EFIB_LP_1B`. The problem is with the TCT products `SW_EXPT_EFIB_TCT02` & `SW_EXPT_EFIB_TCT16` - is that what you were accessing? 

```python
import datetime as dt
import matplotlib.pyplot as plt
from viresclient import SwarmRequest

start_time=dt.datetime(2022, 12, 19, 13, 0)
end_time=dt.datetime(2022, 12, 19, 15, 0)

request = SwarmRequest()
request.set_collection('SW_OPER_EFIB_LP_1B', verbose=False)
request.set_products()
data = request.get_between(
    start_time=start_time,
    end_time=end_time,
    asynchronous=False,
    show_progress=False,
)
ds_EFI_LP = data.as_xarray()

request = SwarmRequest()
request.set_collection('SW_EXPT_EFIB_TCT02', verbose=False)
request.set_products()
data = request.get_between(
    start_time=start_time,
    end_time=end_time,
    asynchronous=False,
    show_progress=False,
)
ds_TCT = data.as_xarray()

ds_TCT_interp = ds_TCT.interp_like(ds_EFI_LP, method="cubic")

(ds_TCT_interp["Latitude"] - ds_EFI_LP["Latitude"]).plot()
plt.ylabel("Latitude difference\nSW_OPER_EFIB_LP_1B\n vs SW_EXPT_EFIB_TCT02");
```
![image](https://github.com/user-attachments/assets/e04fbe59-e8f5-41a4-afaf-7d36195459ac)

**Comment by CassandraAuri** [comment]
Hey @smithara ,

Yes I was accessing the 16Hz SW_EXPT_EFIB_TCT16 and in the demonstration I did with the 2Hz data product for easier demonstration SW_EXPT_EFIB_TCT02. I was overplotting the vector fields (That is between SW_EXPT_EFIB_TCT16 and 'SW_OPER_MAGB_HR_1B') and noticed that there was offset in the latitude reported by the two data products that was much much higher than expected 5meters. 



![image](https://github.com/user-attachments/assets/9c05c049-31b3-40bb-a65d-710d82fd1302)

**Comment by smithara** [comment]
I think @JohnathanBurchill is the provider of these data so can hopefully provide answers!

In the meantime, I would suggest using the reported positions from the L1B dataset (i.e. `SW_OPER_MAGB_HR_1B`) instead

**Comment by smithara** [comment]
@CassandraAuri The issue has been identified in the source data and will be fixed in an upcoming new version soon (version 0401). Thank you for reporting this!
