### ISSUE TITLE
Possibility to relax the requirement on cdflib version?

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#30]
Could it be possible to relax the requirement on the cdflib version, currently set to 'cdflib==0.3.9' to 'cdflib>=0.3.9'?

I'm asking this because of the new cdflib v0.3.12 fixing an issue (MAVENSDC/cdflib#53) occurring while reading 'SyncStatus' variable from Swarm CDF products.

**Comment by smithara** [comment]
Oh yeah I should do that. I was just worried about the forwards compatibility and didn't notice there's newer versions, but I think it should be safe . I'll push the change to the master branch now

**Comment by smithara** [comment]
Ok you should be able to install it with:
`pip install git+https://github.com/ESA-VirES/VirES-Python-Client.git`
(this will get a "version 0.3.1" but will be different from what gets released on pypi later)

**Comment by lmar76** [comment]
Thank you!

**Comment by smithara** [comment]
Now fixed in v0.4.0
