### ISSUE TITLE
ReturnedData.as_xarray raises NotImplementedError with MAGNET q_NEC_CRF parameter

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#33]
Executing the following code:
```python
req = SwarmRequest()
req.set_collection('SW_OPER_MAGA_LR_1B')
req.set_products(measurements=['q_NEC_CRF'])
data = req.get_between(dt.datetime(2019, 1, 1), dt.datetime(2019, 1, 1, 23, 59, 59))
```
The exception below is raised:
```
NotImplementedError: q_NEC_CRF: array too complicated
```

**Comment by smithara** [comment]
Thanks for pointing this out. I'm aware of the issue - I only accounted for three-element vectors in the xarray.Dataset creation. I will have a look into what is an appropriate way to handle the other cases.

**Comment by smithara** [comment]
`q_NEC_CRF` and also `QDBasis` cases are now covered. They get assigned dimension names "dim_2" and ("dim_3" and "dim_4") respectively, just to distinguish them from the existing "dim" dimension name used already for the 3-vector cases.

Eventually this should be replaced by some consistent and logical naming convention.

**Comment by lmar76** [comment]
It works, thank you.
