### ISSUE TITLE
Wrong spacecraft identifier for IPDxIRR_2F products

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#37]
Issue detected on v0.4.

IPDxIRR_2F data retrieved via VirES-Python-Client have ``Spacecraft`` identifiers set to ``-`` (see example: [Spacecraft_issue.zip](https://github.com/ESA-VirES/VirES-Python-Client/files/3556460/Spacecraft_issue.zip))

**Comment by pacesm** [comment]
This is a server side problem - a misconfigration of the VirES production machine.
