### ISSUE TITLE
Token configuration procedure not working via notebook

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#46]
I am testing the token configuration procedure via notebook. 

After deleting the `~/.viresclient.ini`, as indicated in the [VirES-Python-Client’s documentation](https://viresclient.readthedocs.io/en/latest/installation.html#first-usage-configuration), I have executed the following steps:

```python
from viresclient import set_token
set_token("https://vires.services/ows")
```

and I get the following error: 

```
error: (25, 'Inappropriate ioctl for device')
```

See screenshot below:

![image](https://user-images.githubusercontent.com/20207042/73282235-8acf8100-41f1-11ea-890a-e62eefd7f407.png)

**Comment by smithara** [comment]
Thank you for the report

Can you give more information on how you are running Jupyter? Or are you running it on the VRE? I am not able to reproduce the problem on my machine or the VRE.

You can still set the configuration by the other options avoiding  `set_token()` (https://viresclient.readthedocs.io/en/latest/config_details.html#configuration-via-cli)

Anyway I will make a small change to avoid the possibility of this bug in the future.

**Comment by lmar76** [comment]
@smithara I tried again and the error does not occur anymore. I am sorry but I don't understand why I got this error yesterday.

**Comment by smithara** [comment]
No problem. We think it is just a very rare glitch with `getpass` but can't see exactly the cause right now, but should always work again just when the code is re-run / kernel restarted. I will close the ticket in a few days when I've made some change to work around this case.
