### ISSUE TITLE
Cannot see uploaded data in the web gui

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#47]
I tried to upload a product to the server executing the following code:

```python
from viresclient import ClientConfig, DataUpload, SwarmRequest

# download product from server
request = SwarmRequest()
request.set_collection('SW_OPER_MAGA_LR_1B')
request.set_products(measurements=['F', 'B_NEC'])
data = request.get_between('2020-01-01T00:00:00', '2020-01-01T01:00:00')
data.to_file('out.cdf', True)

# upload the product to the server
cc = ClientConfig()
du = DataUpload(cc.default_url, cc.get_site_config(cc.default_url)['token'])
info = du.post('out.cdf', 'test')
```
The upload was successful (i.e. progress bar up to 100%, no errors) but in the web interface I can't see the uploaded data.

**Comment by pacesm** [comment]
@lmar76 I checked the server and the uploaded file `test` is there. I suspect the issue is causes by the missing `cdf`extension. The `spacepy.pycdf` library cannot open CDF files without the `.cdf` extension.

**Comment by pacesm** [comment]
Server-side problem. Replaced by https://github.com/ESA-VirES/WebClient-Framework/issues/390
