### ISSUE TITLE
URL of the access token generation page incorrect

### ISSUE THREAD

**Issue by lmar76** [ESA-VirES/VirES-Python-Client#48]
The URL of the access token generation GUI, prompted during the notebook execution if the token is not configured, is incorrect:

https://staging.vires.services/accounts/tokens//accounts/tokens/

<img width="744" alt="immagine" src="https://user-images.githubusercontent.com/20207042/83134584-df720280-a0e4-11ea-8e63-77a5bfbae691.png">

<img width="1552" alt="immagine" src="https://user-images.githubusercontent.com/20207042/83134629-edc01e80-a0e4-11ea-877c-1c9ad689842f.png">

**Comment by pacesm** [comment]
FYI, this regression has been already fixed in the repo in https://github.com/ESA-VirES/VirES-Python-Client/commit/f342a11dabb42518137fcc1b2e1e6591d88bf0be.

VRE-staging image has not been updated yet, though.

**Comment by pacesm** [comment]
The Docker image has been updated. After you restart your server you should get the correct URL.

**Comment by lmar76** [comment]
It works, thank you.
