### ISSUE TITLE
Issue with SH degree model manipulation for LCS-1 and CHAOS

### ISSUE THREAD

**Issue by mikkelotzen** [ESA-VirES/VirES-Python-Client#56]
By following the readthedocs notebook at: https://swarm-vre.readthedocs.io/en/latest/Swarm_notebooks/02b__viresclient-Available-Data.html

I have been trying to load observations along with models truncated at various SH degrees e.g. 

```
request.set_collection("SW_OPER_MAGA_LR_1B")

request.set_products(measurements=["B_NEC"],
                     models = use_models,
                     auxiliaries=["SunZenithAngle", "Kp", "QDLat", "Dst", "IMF_BZ_GSM"],
                     residuals=False,
                     sampling_step="PT5M")

data = request.get_between(start_time=dt.datetime(2019,7,1),
                           end_time=dt.datetime(2019,12,1))
```

Where I have tried use_models as

```
use_models = {"LCS1": "LCS-1(min_degree=21, max_degree=185)", "CHAOS": "CHAOS(min_degree=14, max_degree=20)", "MIO_SHA_2C": "MIO_SHA_2C"}

use_models = ["LCS1=LCS-1(min_degree=21, max_degree=185)", "CHAOS=CHAOS(min_degree=14, max_degree=20)", "MIO_SHA_2C"]
```

This does not seem to work for LCS-1 and CHAOS. It does seem to work with for instance MCO_SHA_2C.

Am I doing something wrong or is there an issue?

Error output:

```
---------------------------------------------------------------------------
WPSError                                  Traceback (most recent call last)
~/miniconda3/envs/seqsim/lib/python3.8/site-packages/viresclient/_client.py in _get(self, request, asynchronous, response_handler, message, show_progress)
    427                         # progressbar.write(message)
--> 428                         return self._wps_service.retrieve_async(
    429                             request,

~/miniconda3/envs/seqsim/lib/python3.8/site-packages/viresclient/_wps/wps.py in retrieve_async(self, request, handler, status_handler, cleanup_handler, polling_interval, output_name)
    162                 ows_exception, namespace = self.find_exception(wpsstatus.execute_response)
--> 163                 raise self.parse_ows_exception(ows_exception, namespace)
    164 

WPSError: WPS Request Failed! Reason: InvalidParameterValue [model_ids]: Invalid input value of 'model_ids'! Invalid model list! Illegal character '1', line 1, column 10!

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-77e77ccd2747> in <module>
      7                      sampling_step="PT5M")
      8 
----> 9 data = request.get_between(start_time=dt.datetime(2016,7,1),
     10                            end_time=dt.datetime(2016,12,1))
     11 

~/miniconda3/envs/seqsim/lib/python3.8/site-packages/viresclient/_client.py in get_between(self, start_time, end_time, filetype, asynchronous, show_progress, nrecords_limit, tmpdir)
    549                 retdatafile, show_progress=show_progress
    550                 )
--> 551             self._get(
    552                 request=self._request,
    553                 asynchronous=asynchronous,

~/miniconda3/envs/seqsim/lib/python3.8/site-packages/viresclient/_client.py in _get(self, request, asynchronous, response_handler, message, show_progress)
    442                 )
    443         except WPSError:
--> 444             raise RuntimeError(
    445                 "Server error. Or perhaps the request is invalid? "
    446                 "Check the output of: print(request) and "

RuntimeError: Server error. Or perhaps the request is invalid? Check the output of: print(request) and print(request._request.decode())
```

print(request):

```
Request details:
collection_ids: {'Alpha': ['SW_OPER_MAGA_LR_1B']}
model_expression: LCS1=LCS-1(max_degree=21, min_degree=185),CHAOS=CHAOS(min_degree=14, max_degree=20),MIO_SHA_2C=MIO_SHA_2C
begin_time: 2016-07-01 00:00:00
end_time: 2016-12-01 00:00:00
variables: ['B_NEC', 'B_NEC_LCS1', 'B_NEC_CHAOS', 'B_NEC_MIO_SHA_2C', 'SunZenithAngle', 'Kp', 'QDLat', 'Dst', 'IMF_BZ_GSM']
filters: None
sampling_step: PT5M
response_type: application/x-cdf
custom_shc: None
```

**Comment by pacesm** [comment]
Hi @mikkelotzen,

the table below lists all magnetic model identifiers available VirES and corresponding expressions to which they are expanded when evaluated by the server.

As you can see, there are simple modes such as `AMPS`, `CHAOS-Core`, `CHAOS-MMA-Primary`, `CHAOS-MMA-Secondary`, `CHAOS-Static`, `IGRF`, `LCS-1`, ... etc. and composed ones such as `CHAOS`, `CHAOS-MMA`, `SwarmCI`, ... etc.

E.g., the simple model `CHAOS-Core` is expanded and evaluated as `'CHAOS-Core'(max_degree=20,min_degree=1)`. The composed `CHAOS` model is then evaluated as a sum of the following simple models:
+ `'CHAOS-Core'(max_degree=20,min_degree=1)`
+ `'CHAOS-Static'(max_degree=185,min_degree=21)`
+ `'CHAOS-MMA-Primary'(max_degree=2,min_degree=1)`
+ `'CHAOS-MMA-Secondary'(max_degree=2,min_degree=1)`

and it is equivalent to requesting
 ``` 
CHAOS = 'CHAOS-Core'(max_degree=20,min_degree=1) + 'CHAOS-Static'(max_degree=185,min_degree=21) + 'CHAOS-MMA-Primary'(max_degree=2,min_degree=1) + 'CHAOS-MMA-Secondary'(max_degree=2,min_degree=1)
```

With exception of the AMPS model, all simple SH models allow selection min. and max. degree parameters . Composed models do not allow selection of these parameters as it may not always be clear how apply them to the simple models. The composed models thus work as convenience shortcuts. If you need compose model with custom degree ranges you have to build your own one from the simple SH models.

Please also note the quoted model identifiers containing the dash (`-`) character. This is required to prevent interpretation of the dash as subtraction (i.e.,`CHAOS-Core` and not `CHAOS` minus `Core`).

Specifically, in your case, you need to quote the `LCS-1` model:
```
'LCS-1'(max_degree=185,min_degree=21)
```
and use  the full model expression for the `CHAOS` model:
```
'CHAOS-Core'(max_degree=20,min_degree=14) + 'CHAOS-MMA-Primary'(max_degree=2,min_degree=1) + 'CHAOS-MMA-Secondary'(max_degree=2,min_degree=1)
```
 (I left out the `CHAOS-Static` model)

mode id | model expression
--- | ---
AMPS | AMPS()
CHAOS | 'CHAOS-Core'(max_degree=20,min_degree=1) + 'CHAOS-Static'(max_degree=185,min_degree=21) + 'CHAOS-MMA-Primary'(max_degree=2,min_degree=1) + 'CHAOS-MMA-Secondary'(max_degree=2,min_degree=1)
CHAOS-Core | 'CHAOS-Core'(max_degree=20,min_degree=1)
CHAOS-MMA | 'CHAOS-MMA-Primary'(max_degree=2,min_degree=1) + 'CHAOS-MMA-Secondary'(max_degree=2,min_degree=1)
CHAOS-MMA-Primary | 'CHAOS-MMA-Primary'(max_degree=2,min_degree=1)
CHAOS-MMA-Secondary | 'CHAOS-MMA-Secondary'(max_degree=2,min_degree=1)
CHAOS-Static | 'CHAOS-Static'(max_degree=185,min_degree=21)
IGRF | IGRF(max_degree=13,min_degree=1)
LCS-1 | 'LCS-1'(max_degree=185,min_degree=1)
MCO_SHA_2C | MCO_SHA_2C(max_degree=18,min_degree=1)
MCO_SHA_2D | MCO_SHA_2D(max_degree=20,min_degree=1)
MCO_SHA_2X | 'CHAOS-Core'(max_degree=20,min_degree=1)
MF7 | MF7(max_degree=133,min_degree=16)
MIO_SHA_2C | 'MIO_SHA_2C-Primary'(max_degree=60,min_degree=1) + 'MIO_SHA_2C-Secondary'(max_degree=60,min_degree=1)
MIO_SHA_2C-Primary | 'MIO_SHA_2C-Primary'(max_degree=60,min_degree=1)
MIO_SHA_2C-Secondary | 'MIO_SHA_2C-Secondary'(max_degree=60,min_degree=1)
MIO_SHA_2D | 'MIO_SHA_2D-Primary'(max_degree=60,min_degree=1) + 'MIO_SHA_2D-Secondary'(max_degree=60,min_degree=1)
MIO_SHA_2D-Primary | 'MIO_SHA_2D-Primary'(max_degree=60,min_degree=1)
MIO_SHA_2D-Secondary | 'MIO_SHA_2D-Secondary'(max_degree=60,min_degree=1)
MLI_SHA_2C | MLI_SHA_2C(max_degree=120,min_degree=16)
MLI_SHA_2D | MLI_SHA_2D(max_degree=133,min_degree=16)
MLI_SHA_2E | MLI_SHA_2E(max_degree=200,min_degree=16)
MMA_SHA_2C | 'MMA_SHA_2C-Primary'(max_degree=2,min_degree=1) + 'MMA_SHA_2C-Secondary'(max_degree=3,min_degree=1)
MMA_SHA_2C-Primary | 'MMA_SHA_2C-Primary'(max_degree=2,min_degree=1)
MMA_SHA_2C-Secondary | 'MMA_SHA_2C-Secondary'(max_degree=3,min_degree=1)
MMA_SHA_2F | 'MMA_SHA_2F-Primary'(max_degree=1,min_degree=1) + 'MMA_SHA_2F-Secondary'(max_degree=1,min_degree=1)
MMA_SHA_2F-Primary | 'MMA_SHA_2F-Primary'(max_degree=1,min_degree=1)
MMA_SHA_2F-Secondary | 'MMA_SHA_2F-Secondary'(max_degree=1,min_degree=1)
SwarmCI | MCO_SHA_2C(max_degree=18,min_degree=1) + MLI_SHA_2C(max_degree=120,min_degree=16) + 'MMA_SHA_2C-Primary'(max_degree=2,min_degree=1) + 'MMA_SHA_2C-Secondary'(max_degree=3,min_degree=1) + 'MIO_SHA_2C-Primary'(max_degree=60,min_degree=1) + 'MIO_SHA_2C-Secondary'(max_degree=60,min_degree=1)

**Comment by smithara** [comment]
In short, what you are looking for is
```
use_models = ["LCS1='LCS-1'(min_degree=21, max_degree=185)", "CHAOS='CHAOS-Core'(min_degree=14, max_degree=20)", "MIO_SHA_2C"]
```
(assuming you don't want the magnetospheric components of CHAOS)

Another thing: for the "IMF_BZ_GSM" - this is a time averaged value rather than the original 1min/5min from OMNI. If you want more fine control you can fetch data using [hapiclient](https://github.com/hapi-server/client-python) - I'm working on an example of using it [here](https://deepnote.com/publish/82de274e-c2bc-4276-91f4-b840809f16e4) for a space weather demo to be part of `Swarm_notebooks`

**Comment by mikkelotzen** [comment]
Hi @pacesm and @smithara 

Thank you for the elaborate responses

I see your point about the simple versus pre-composed models, that makes sense. Also the quotes. It now works!

When it wasn't working I did try just with LCS-1 and obviously still got it wrong due to the lack of quotes. I think what led me off was this part in the notebook I linked (the section on manipulation of models)

> Model details can be found with request.get_model_info(models=...) which handles **the same models input as set_products()**. This information is returned as a dictionary.

Emphasis mine. Followed by

```
# Demonstrates:
#  limiting SH degree
#  providing your own model file
#  referring to defined models
request.get_model_info(
    models=[
        "MLI_SHA_2D = MLI_SHA_2D(min_degree=1, max_degree=80)",
        "LCS = Custom_Model(min_degree=1, max_degree=80)",
        "LCS-SwarmMLI = LCS - MLI_SHA_2D"
    ],
    custom_model=file_name,
)
```

Where there is no quotes around the model designation before the min/max degree call. Some distinction/further elaboration may be needed here.

I take note on what you mentioned with regards to IMF_BZ_GSM, thanks for letting me know. I will certainly follow your example.

Again, thank you so much for solving this for me :-) See you around!
