### ISSUE TITLE
Broken with cdflib 0.3.20

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/VirES-Python-Client#57]
File reads under cdflib 0.3.20 (released Jan 5) seem to be broken. A simple request and attempting to load the data fails:

```
!pip install "cdflib==0.3.20"

import datetime as dt
from viresclient import SwarmRequest

request = SwarmRequest()
request.set_collection("SW_OPER_MAGA_LR_1B")
request.set_products(measurements=["F"])
data = request.get_between(start_time=dt.datetime(2016,1,1),
                           end_time=dt.datetime(2016,1,2))

df = data.as_dataframe()
```
gives
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
```

<details><pre>
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-1-a72d0f2e950e> in <module>
     10                            end_time=dt.datetime(2016,1,2))
     11 
---> 12 df = data.as_dataframe()

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in as_dataframe(self, expand)
    619         """
    620         return pandas.concat(
--> 621             [d.as_dataframe(expand=expand) for d in self.contents])
    622 
    623     def as_xarray(self, reshape=False):

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in <listcomp>(.0)
    619         """
    620         return pandas.concat(
--> 621             [d.as_dataframe(expand=expand) for d in self.contents])
    622 
    623     def as_xarray(self, reshape=False):

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in as_dataframe(self, expand)
    472             df = make_pandas_DataFrame_from_csv(self._file.name)
    473         elif self.filetype == 'cdf':
--> 474             with FileReader(self._file) as f:
    475                 df = f.as_pandas_dataframe(expand=expand)
    476         return df

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in __init__(self, file, filetype)
     97             self.variables = self._cdf.cdf_info()['zVariables']
     98             self._varatts = {var: self._cdf.varattsget(var)
---> 99                              for var in self.variables}
    100             self._varinfo = {var: self._cdf.varinq(var)
    101                              for var in self.variables}

/opt/conda/lib/python3.7/site-packages/viresclient/_data_handling.py in <dictcomp>(.0)
     97             self.variables = self._cdf.cdf_info()['zVariables']
     98             self._varatts = {var: self._cdf.varattsget(var)
---> 99                              for var in self.variables}
    100             self._varinfo = {var: self._cdf.varinq(var)
    101                              for var in self.variables}

/opt/conda/lib/python3.7/site-packages/cdflib/cdfread.py in varattsget(self, variable, expand, to_np)
    683                     if name.strip().lower() == variable.strip().lower():
    684                         vdr_info = self._read_vdr(position)
--> 685                         return self._read_varatts(vdr_info['variable_number'], zVar, expand, to_np=to_np)
    686                     position = vdr_next
    687                 position = self._first_rvariable

/opt/conda/lib/python3.7/site-packages/cdflib/cdfread.py in _read_varatts(self, var_num, zVar, expand, to_np)
   1079                     byte_loc = byte_next
   1080                     continue
-> 1081                 aedr_info = self._read_aedr(byte_loc, to_np=to_np)
   1082                 entryData = aedr_info['entry']
   1083                 if (expand is False):

/opt/conda/lib/python3.7/site-packages/cdflib/cdfread.py in _read_aedr(self, byte_loc, to_np)
   1259             return self._read_aedr3(byte_loc, to_np)
   1260         else:
-> 1261             return self._read_aedr2(byte_loc, to_np)
   1262 
   1263     def _read_aedr3(self, byte_loc, to_np=True):

/opt/conda/lib/python3.7/site-packages/cdflib/cdfread.py in _read_aedr2(self, byte_loc, to_np)
   1327         byte_stream = aedr[44:]
   1328         if to_np:
-> 1329             entry = self._read_data(byte_stream, data_type, 1, num_elements)
   1330         else:
   1331             if (data_type == 32):

/opt/conda/lib/python3.7/site-packages/cdflib/cdfread.py in _read_data(self, byte_stream, data_type, num_recs, num_elems, dimensions)
   1899                     if (z > -1 and z < (num_elems - 1)):
   1900                         byte_data[y + z + 1:y + num_elems] = b'\x00' * (num_elems - z - 1)
-> 1901                 ret = byte_data[0:num_recs*num_elems].decode(self.string_encoding).replace('\x00', '')
   1902             else:
   1903                 # Count total number of strings
</pre></details>

**Comment by smithara** [comment]
The problem is with the character `– ` in `{'DESCRIPTION': 'Position in ITRF – Latitude', 'UNITS': 'deg'}` when doing `cdf_file.varattsget("Latitude")`, the error occurring at https://github.com/MAVENSDC/cdflib/blob/30fe0fdc3db0fc5d23a1caf59f72d2b038687cb1/cdflib/cdfread.py#L1901

**Comment by smithara** [comment]
cdflib 0.3.20 now defaults to ascii encoding. Looks like files should now be read instead like:
```
import cdflib

cdf_file = cdflib.cdfread.CDF('test.cdf', string_encoding="utf-8")
```

**Comment by pacesm** [comment]
The CDF spec formally allows only plain ASCII in the CDF attributes but libraries such as, e.g., the official NASA CDF library, do not check the characters and allow UTF-8 encoded Unicode characters to be inserted.

Therefore is it common that some of the Swarm products (such as e.g. `MAGx_LR`) contain UTF-8 encoded Unicode glyphs in the attributes.

```
CDF variable         DESCRIPTION attribute
------------------------------------------
Timestamp            Time stamp
SyncStatus           Synchronization status
Latitude             Position in ITRF \u2013 Latitude
Longitude            Position in ITRF \u2013 Longitude
Radius               Position in ITRF \u2013 Radius
F                    Magnetic field intensity
dF_AOCS              Magnetic stray field correction intensity of AOCS magneto-torquer coils
dF_other             Magnetic stray field correction intensity of all other sources
F_error              Error estimate on magnetic field intensity
B_VFM                Magnetic field vector, VFM frame
B_NEC                Magnetic field vector, NEC frame
dB_Sun               Magnetic stray field correction vector of Sun induced perturbation, VFM frame
dB_AOCS              Magnetic stray field correction vector of AOCS magneto-torquer coils, VFM frame
dB_other             Magnetic stray field correction vector of all other sources, VFM frame
B_error              Error estimates on magnetic field, VFM frame
q_NEC_CRF            Quaternion, transformation: NEC \u2190 CRF
Att_error            Error estimates on attitude information
Flags_F              Flags characterizing the magnetic field intensity measurement (F)
Flags_B              Flags characterizing the magnetic field measurement
Flags_q              Flags characterizing the attitude information
Flags_Platform       Flags characterizing the S/C platform information
ASM_Freq_Dev         ASM frequency calibration data deviation
```

In VirES we just copy the attributes from the original files.
