### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by HongLouyemeng** [ESA-VirES/VirES-Python-Client#62]
I can't download Aeolus data through the client.
error:'AeolusWPSInputs' object has no attribute 'names'

**Comment by santilland** [comment]
Hello @HongLouyemeng you found this quickly, this is not yet ready. We are working on implementing everything, it will take some time. We are starting to prepare the documentation. Difficult to say when this will be available to the public, but we will announce it through various channels once it is ready.

**Comment by santilland** [comment]
I don't know any library that lets you do it, but you can go to https://aeolus.services and download files as netcdf through your browser. I hope that helps.
