### ISSUE TITLE
Add a default time step to collections

### ISSUE THREAD

**Issue by smithara** [ESA-VirES/VirES-Python-Client#7]
In available_collections, also specify the default time step
  - i.e. identify 1Hz data as 1s etc.
  - required for the correct ``_chunkify_request`` behaviour
  - set this as the default sampling_step
  - will currently break for new non-1Hz data (for collections not hard-coded in)
  - This is currently done with a temporary solution here: https://github.com/ESA-VirES/VirES-Python-Client/blob/fd98111f6b4b57c5b1d02cad57e43f8af4928339/viresclient/_client.py#L474

**Comment by smithara** [comment]
Was fixed a while ago. New collections will default to a guess of 1s to try split long requests (actual returned sampling rate is unaffected, but long requests might go over the limit / be inefficiently chunked if the real sampling rate is higher/lower)

**Comment by pacesm** [comment]
Please note that fixing the sampling to an explicit default value may not be always the best idea. 
While it makes sense to show the nominal sampling in the presentation layer, some of the collection may have irregular sampling (MAGx_HR_1B) and to get all samples from the server it is better to send no sampling at all (default `None`) rather then the nominal value.

Both request templates accept sampling set to `None`:
https://github.com/ESA-VirES/VirES-Python-Client/blob/446a49c0bbad7dcefef0e0b0c3805fa96980265c/viresclient/_wps/templates/vires_fetch_filtered_data_async.xml#L53

https://github.com/ESA-VirES/VirES-Python-Client/blob/446a49c0bbad7dcefef0e0b0c3805fa96980265c/viresclient/_wps/templates/vires_fetch_filtered_data.xml#L53

**Comment by smithara** [comment]
Sorry I wasn't clear here. The template is indeed given `None` for the requests where a `sampling_step` is not specified.

The "default sampling step" referenced here is only used to identify the maximum duration of each sub-request when a user asks for a longer time windows.
