### ISSUE TITLE
SSL certificate error with vscode

### ISSUE THREAD

**Issue by SAR-UCL** [ESA-VirES/VirES-Python-Client#78]
In vscode (mac) `request = SwarmRequest()` returns `SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)`

I've tried disabling the  Proxy Strict SSL tab (bad practice),  but this doesn't sort it either.  I set the access token _before_ the line above, so I presume its not this.

Is this a vscode issue or? Everything works fine within the VRE

**Comment by pacesm** [comment]
The error says that the `openssl` library is not able to verify the server SSL certificate and it prevents secure connection to the VirES server. It seems like the version of the `openssl` does not recognize the Let's encrypt certification authority. It could be related to the recent [expiration of the Let's encrypt root certificate](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/).

I'd recommend to upgrade your software. My guess is that `vscode` bundles own version of the `openssl` library and  I'd therefore start with `vscode` first.

Note that issue has nothing to do with your access token or the functionality of the VirES client.

**Comment by SAR-UCL** [comment]
Thanks for your advise. Can't find a workaround, so i'll stick with the online VirES client.
